### ISSUE TITLE
Need proper documentation

### ISSUE THREAD

**Issue by aromalanil** [aromalanil/react-rhino#1]
The current documentation is not that great. We need a better documentation for the package.

Open for contributions.

**Comment by naftalimurgor** [comment]
Hey @aromalanil 
I made a few changes to the documentation as mentioned in this issue. I'll submit a pull request for the changes. Let me know what you think. Thank you.

**Comment by aromalanil** [comment]
@naftalimurgor 
That would be great. Always open for PR

**Comment by naftalimurgor** [comment]
Great!. Will submit shortly. Thanks

**Comment by naftalimurgor** [comment]
@aromalanil  
Glad I could help 🎊
